#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet2BaseDeDonnees3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD5B6TP2Marrero_Kouma")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertAbonnements(Abonnements instance);
    partial void UpdateAbonnements(Abonnements instance);
    partial void DeleteAbonnements(Abonnements instance);
    partial void InsertDependants(Dependants instance);
    partial void UpdateDependants(Dependants instance);
    partial void DeleteDependants(Dependants instance);
    partial void InsertDepenses(Depenses instance);
    partial void UpdateDepenses(Depenses instance);
    partial void DeleteDepenses(Depenses instance);
    partial void InsertEmployes(Employes instance);
    partial void UpdateEmployes(Employes instance);
    partial void DeleteEmployes(Employes instance);
    partial void InsertPartiesJouees(PartiesJouees instance);
    partial void UpdatePartiesJouees(PartiesJouees instance);
    partial void DeletePartiesJouees(PartiesJouees instance);
    partial void InsertPrixDepensesAbonnements(PrixDepensesAbonnements instance);
    partial void UpdatePrixDepensesAbonnements(PrixDepensesAbonnements instance);
    partial void DeletePrixDepensesAbonnements(PrixDepensesAbonnements instance);
    partial void InsertProvinces(Provinces instance);
    partial void UpdateProvinces(Provinces instance);
    partial void DeleteProvinces(Provinces instance);
    partial void InsertReabonnements(Reabonnements instance);
    partial void UpdateReabonnements(Reabonnements instance);
    partial void DeleteReabonnements(Reabonnements instance);
    partial void InsertServices(Services instance);
    partial void UpdateServices(Services instance);
    partial void DeleteServices(Services instance);
    partial void InsertTerrains(Terrains instance);
    partial void UpdateTerrains(Terrains instance);
    partial void DeleteTerrains(Terrains instance);
    partial void InsertTypesAbonnement(TypesAbonnement instance);
    partial void UpdateTypesAbonnement(TypesAbonnement instance);
    partial void DeleteTypesAbonnement(TypesAbonnement instance);
    partial void InsertTypesEmploye(TypesEmploye instance);
    partial void UpdateTypesEmploye(TypesEmploye instance);
    partial void DeleteTypesEmploye(TypesEmploye instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::projet2BaseDeDonnees3.Properties.Settings.Default.BD5B6TP2Marrero_KoumaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Abonnements> Abonnements
		{
			get
			{
				return this.GetTable<Abonnements>();
			}
		}
		
		public System.Data.Linq.Table<Dependants> Dependants
		{
			get
			{
				return this.GetTable<Dependants>();
			}
		}
		
		public System.Data.Linq.Table<Depenses> Depenses
		{
			get
			{
				return this.GetTable<Depenses>();
			}
		}
		
		public System.Data.Linq.Table<Employes> Employes
		{
			get
			{
				return this.GetTable<Employes>();
			}
		}
		
		public System.Data.Linq.Table<PartiesJouees> PartiesJouees
		{
			get
			{
				return this.GetTable<PartiesJouees>();
			}
		}
		
		public System.Data.Linq.Table<PrixDepensesAbonnements> PrixDepensesAbonnements
		{
			get
			{
				return this.GetTable<PrixDepensesAbonnements>();
			}
		}
		
		public System.Data.Linq.Table<Provinces> Provinces
		{
			get
			{
				return this.GetTable<Provinces>();
			}
		}
		
		public System.Data.Linq.Table<Reabonnements> Reabonnements
		{
			get
			{
				return this.GetTable<Reabonnements>();
			}
		}
		
		public System.Data.Linq.Table<Services> Services
		{
			get
			{
				return this.GetTable<Services>();
			}
		}
		
		public System.Data.Linq.Table<Terrains> Terrains
		{
			get
			{
				return this.GetTable<Terrains>();
			}
		}
		
		public System.Data.Linq.Table<TypesAbonnement> TypesAbonnement
		{
			get
			{
				return this.GetTable<TypesAbonnement>();
			}
		}
		
		public System.Data.Linq.Table<TypesEmploye> TypesEmploye
		{
			get
			{
				return this.GetTable<TypesEmploye>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Abonnements")]
	public partial class Abonnements : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private System.DateTime _DateAbonnement;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Sexe;
		
		private System.DateTime _DateNaissance;
		
		private int _NoCivique;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _IdProvince;
		
		private string _CodePostal;
		
		private string _Telephone;
		
		private string _Cellulaire;
		
		private string _Courriel;
		
		private int _NoTypeAbonnement;
		
		private string _Remarque;
		
		private EntitySet<Dependants> _Dependants;
		
		private EntitySet<Depenses> _Depenses;
		
		private EntitySet<PartiesJouees> _PartiesJouees;
		
		private EntitySet<Reabonnements> _Reabonnements;
		
		private EntityRef<Provinces> _Provinces;
		
		private EntityRef<TypesAbonnement> _TypesAbonnement;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnDateAbonnementChanging(System.DateTime value);
    partial void OnDateAbonnementChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnDateNaissanceChanging(System.DateTime value);
    partial void OnDateNaissanceChanged();
    partial void OnNoCiviqueChanging(int value);
    partial void OnNoCiviqueChanged();
    partial void OnRueChanging(string value);
    partial void OnRueChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnIdProvinceChanging(string value);
    partial void OnIdProvinceChanged();
    partial void OnCodePostalChanging(string value);
    partial void OnCodePostalChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnCellulaireChanging(string value);
    partial void OnCellulaireChanged();
    partial void OnCourrielChanging(string value);
    partial void OnCourrielChanged();
    partial void OnNoTypeAbonnementChanging(int value);
    partial void OnNoTypeAbonnementChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Abonnements()
		{
			this._Dependants = new EntitySet<Dependants>(new Action<Dependants>(this.attach_Dependants), new Action<Dependants>(this.detach_Dependants));
			this._Depenses = new EntitySet<Depenses>(new Action<Depenses>(this.attach_Depenses), new Action<Depenses>(this.detach_Depenses));
			this._PartiesJouees = new EntitySet<PartiesJouees>(new Action<PartiesJouees>(this.attach_PartiesJouees), new Action<PartiesJouees>(this.detach_PartiesJouees));
			this._Reabonnements = new EntitySet<Reabonnements>(new Action<Reabonnements>(this.attach_Reabonnements), new Action<Reabonnements>(this.detach_Reabonnements));
			this._Provinces = default(EntityRef<Provinces>);
			this._TypesAbonnement = default(EntityRef<TypesAbonnement>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAbonnement", DbType="Date NOT NULL")]
		public System.DateTime DateAbonnement
		{
			get
			{
				return this._DateAbonnement;
			}
			set
			{
				if ((this._DateAbonnement != value))
				{
					this.OnDateAbonnementChanging(value);
					this.SendPropertyChanging();
					this._DateAbonnement = value;
					this.SendPropertyChanged("DateAbonnement");
					this.OnDateAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateNaissance", DbType="Date NOT NULL")]
		public System.DateTime DateNaissance
		{
			get
			{
				return this._DateNaissance;
			}
			set
			{
				if ((this._DateNaissance != value))
				{
					this.OnDateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._DateNaissance = value;
					this.SendPropertyChanged("DateNaissance");
					this.OnDateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCivique", DbType="Int NOT NULL")]
		public int NoCivique
		{
			get
			{
				return this._NoCivique;
			}
			set
			{
				if ((this._NoCivique != value))
				{
					this.OnNoCiviqueChanging(value);
					this.SendPropertyChanging();
					this._NoCivique = value;
					this.SendPropertyChanged("NoCivique");
					this.OnNoCiviqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this.OnRueChanging(value);
					this.SendPropertyChanging();
					this._Rue = value;
					this.SendPropertyChanged("Rue");
					this.OnRueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProvince", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string IdProvince
		{
			get
			{
				return this._IdProvince;
			}
			set
			{
				if ((this._IdProvince != value))
				{
					if (this._Provinces.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProvinceChanging(value);
					this.SendPropertyChanging();
					this._IdProvince = value;
					this.SendPropertyChanged("IdProvince");
					this.OnIdProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostal", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string CodePostal
		{
			get
			{
				return this._CodePostal;
			}
			set
			{
				if ((this._CodePostal != value))
				{
					this.OnCodePostalChanging(value);
					this.SendPropertyChanging();
					this._CodePostal = value;
					this.SendPropertyChanged("CodePostal");
					this.OnCodePostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cellulaire", DbType="VarChar(10)")]
		public string Cellulaire
		{
			get
			{
				return this._Cellulaire;
			}
			set
			{
				if ((this._Cellulaire != value))
				{
					this.OnCellulaireChanging(value);
					this.SendPropertyChanging();
					this._Cellulaire = value;
					this.SendPropertyChanged("Cellulaire");
					this.OnCellulaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Courriel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Courriel
		{
			get
			{
				return this._Courriel;
			}
			set
			{
				if ((this._Courriel != value))
				{
					this.OnCourrielChanging(value);
					this.SendPropertyChanging();
					this._Courriel = value;
					this.SendPropertyChanged("Courriel");
					this.OnCourrielChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTypeAbonnement", DbType="Int NOT NULL")]
		public int NoTypeAbonnement
		{
			get
			{
				return this._NoTypeAbonnement;
			}
			set
			{
				if ((this._NoTypeAbonnement != value))
				{
					if (this._TypesAbonnement.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoTypeAbonnementChanging(value);
					this.SendPropertyChanging();
					this._NoTypeAbonnement = value;
					this.SendPropertyChanged("NoTypeAbonnement");
					this.OnNoTypeAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_Dependants", Storage="_Dependants", ThisKey="Id", OtherKey="IdAbonnement")]
		public EntitySet<Dependants> Dependants
		{
			get
			{
				return this._Dependants;
			}
			set
			{
				this._Dependants.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_Depenses", Storage="_Depenses", ThisKey="Id", OtherKey="IdAbonnement")]
		public EntitySet<Depenses> Depenses
		{
			get
			{
				return this._Depenses;
			}
			set
			{
				this._Depenses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_PartiesJouees", Storage="_PartiesJouees", ThisKey="Id", OtherKey="IdAbonnement")]
		public EntitySet<PartiesJouees> PartiesJouees
		{
			get
			{
				return this._PartiesJouees;
			}
			set
			{
				this._PartiesJouees.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_Reabonnements", Storage="_Reabonnements", ThisKey="Id", OtherKey="IdAbonnement")]
		public EntitySet<Reabonnements> Reabonnements
		{
			get
			{
				return this._Reabonnements;
			}
			set
			{
				this._Reabonnements.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provinces_Abonnements", Storage="_Provinces", ThisKey="IdProvince", OtherKey="Id", IsForeignKey=true)]
		public Provinces Provinces
		{
			get
			{
				return this._Provinces.Entity;
			}
			set
			{
				Provinces previousValue = this._Provinces.Entity;
				if (((previousValue != value) 
							|| (this._Provinces.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provinces.Entity = null;
						previousValue.Abonnements.Remove(this);
					}
					this._Provinces.Entity = value;
					if ((value != null))
					{
						value.Abonnements.Add(this);
						this._IdProvince = value.Id;
					}
					else
					{
						this._IdProvince = default(string);
					}
					this.SendPropertyChanged("Provinces");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypesAbonnement_Abonnements", Storage="_TypesAbonnement", ThisKey="NoTypeAbonnement", OtherKey="No", IsForeignKey=true)]
		public TypesAbonnement TypesAbonnement
		{
			get
			{
				return this._TypesAbonnement.Entity;
			}
			set
			{
				TypesAbonnement previousValue = this._TypesAbonnement.Entity;
				if (((previousValue != value) 
							|| (this._TypesAbonnement.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TypesAbonnement.Entity = null;
						previousValue.Abonnements.Remove(this);
					}
					this._TypesAbonnement.Entity = value;
					if ((value != null))
					{
						value.Abonnements.Add(this);
						this._NoTypeAbonnement = value.No;
					}
					else
					{
						this._NoTypeAbonnement = default(int);
					}
					this.SendPropertyChanged("TypesAbonnement");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dependants(Dependants entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = this;
		}
		
		private void detach_Dependants(Dependants entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = null;
		}
		
		private void attach_Depenses(Depenses entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = this;
		}
		
		private void detach_Depenses(Depenses entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = null;
		}
		
		private void attach_PartiesJouees(PartiesJouees entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = this;
		}
		
		private void detach_PartiesJouees(PartiesJouees entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = null;
		}
		
		private void attach_Reabonnements(Reabonnements entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = this;
		}
		
		private void detach_Reabonnements(Reabonnements entity)
		{
			this.SendPropertyChanging();
			entity.Abonnements = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dependants")]
	public partial class Dependants : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Sexe;
		
		private System.DateTime _DateNaissance;
		
		private string _IdAbonnement;
		
		private string _Remarque;
		
		private EntityRef<Abonnements> _Abonnements;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnDateNaissanceChanging(System.DateTime value);
    partial void OnDateNaissanceChanged();
    partial void OnIdAbonnementChanging(string value);
    partial void OnIdAbonnementChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Dependants()
		{
			this._Abonnements = default(EntityRef<Abonnements>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateNaissance", DbType="Date NOT NULL")]
		public System.DateTime DateNaissance
		{
			get
			{
				return this._DateNaissance;
			}
			set
			{
				if ((this._DateNaissance != value))
				{
					this.OnDateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._DateNaissance = value;
					this.SendPropertyChanged("DateNaissance");
					this.OnDateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAbonnement", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IdAbonnement
		{
			get
			{
				return this._IdAbonnement;
			}
			set
			{
				if ((this._IdAbonnement != value))
				{
					if (this._Abonnements.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAbonnementChanging(value);
					this.SendPropertyChanging();
					this._IdAbonnement = value;
					this.SendPropertyChanged("IdAbonnement");
					this.OnIdAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_Dependants", Storage="_Abonnements", ThisKey="IdAbonnement", OtherKey="Id", IsForeignKey=true)]
		public Abonnements Abonnements
		{
			get
			{
				return this._Abonnements.Entity;
			}
			set
			{
				Abonnements previousValue = this._Abonnements.Entity;
				if (((previousValue != value) 
							|| (this._Abonnements.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Abonnements.Entity = null;
						previousValue.Dependants.Remove(this);
					}
					this._Abonnements.Entity = value;
					if ((value != null))
					{
						value.Dependants.Add(this);
						this._IdAbonnement = value.Id;
					}
					else
					{
						this._IdAbonnement = default(string);
					}
					this.SendPropertyChanged("Abonnements");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Depenses")]
	public partial class Depenses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _IdAbonnement;
		
		private System.DateTime _DateDepense;
		
		private decimal _Montant;
		
		private int _NoService;
		
		private string _Remarque;
		
		private EntityRef<Abonnements> _Abonnements;
		
		private EntityRef<Services> _Services;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnIdAbonnementChanging(string value);
    partial void OnIdAbonnementChanged();
    partial void OnDateDepenseChanging(System.DateTime value);
    partial void OnDateDepenseChanged();
    partial void OnMontantChanging(decimal value);
    partial void OnMontantChanged();
    partial void OnNoServiceChanging(int value);
    partial void OnNoServiceChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Depenses()
		{
			this._Abonnements = default(EntityRef<Abonnements>);
			this._Services = default(EntityRef<Services>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAbonnement", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IdAbonnement
		{
			get
			{
				return this._IdAbonnement;
			}
			set
			{
				if ((this._IdAbonnement != value))
				{
					if (this._Abonnements.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAbonnementChanging(value);
					this.SendPropertyChanging();
					this._IdAbonnement = value;
					this.SendPropertyChanged("IdAbonnement");
					this.OnIdAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDepense", DbType="Date NOT NULL")]
		public System.DateTime DateDepense
		{
			get
			{
				return this._DateDepense;
			}
			set
			{
				if ((this._DateDepense != value))
				{
					this.OnDateDepenseChanging(value);
					this.SendPropertyChanging();
					this._DateDepense = value;
					this.SendPropertyChanged("DateDepense");
					this.OnDateDepenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montant", DbType="Money NOT NULL")]
		public decimal Montant
		{
			get
			{
				return this._Montant;
			}
			set
			{
				if ((this._Montant != value))
				{
					this.OnMontantChanging(value);
					this.SendPropertyChanging();
					this._Montant = value;
					this.SendPropertyChanged("Montant");
					this.OnMontantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoService", DbType="Int NOT NULL")]
		public int NoService
		{
			get
			{
				return this._NoService;
			}
			set
			{
				if ((this._NoService != value))
				{
					if (this._Services.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoServiceChanging(value);
					this.SendPropertyChanging();
					this._NoService = value;
					this.SendPropertyChanged("NoService");
					this.OnNoServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_Depenses", Storage="_Abonnements", ThisKey="IdAbonnement", OtherKey="Id", IsForeignKey=true)]
		public Abonnements Abonnements
		{
			get
			{
				return this._Abonnements.Entity;
			}
			set
			{
				Abonnements previousValue = this._Abonnements.Entity;
				if (((previousValue != value) 
							|| (this._Abonnements.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Abonnements.Entity = null;
						previousValue.Depenses.Remove(this);
					}
					this._Abonnements.Entity = value;
					if ((value != null))
					{
						value.Depenses.Add(this);
						this._IdAbonnement = value.Id;
					}
					else
					{
						this._IdAbonnement = default(string);
					}
					this.SendPropertyChanged("Abonnements");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Services_Depenses", Storage="_Services", ThisKey="NoService", OtherKey="No", IsForeignKey=true)]
		public Services Services
		{
			get
			{
				return this._Services.Entity;
			}
			set
			{
				Services previousValue = this._Services.Entity;
				if (((previousValue != value) 
							|| (this._Services.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Services.Entity = null;
						previousValue.Depenses.Remove(this);
					}
					this._Services.Entity = value;
					if ((value != null))
					{
						value.Depenses.Add(this);
						this._NoService = value.No;
					}
					else
					{
						this._NoService = default(int);
					}
					this.SendPropertyChanged("Services");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employes")]
	public partial class Employes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _MotDePasse;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Sexe;
		
		private int _Age;
		
		private int _NoCivique;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _IdProvince;
		
		private string _CodePostal;
		
		private string _Telephone;
		
		private string _Cellulaire;
		
		private string _Courriel;
		
		private int _SalaireHoraire;
		
		private int _NoTypeEmploye;
		
		private string _Remarque;
		
		private EntitySet<Services> _Services;
		
		private EntityRef<Provinces> _Provinces;
		
		private EntityRef<TypesEmploye> _TypesEmploye;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnMotDePasseChanging(string value);
    partial void OnMotDePasseChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnAgeChanging(int value);
    partial void OnAgeChanged();
    partial void OnNoCiviqueChanging(int value);
    partial void OnNoCiviqueChanged();
    partial void OnRueChanging(string value);
    partial void OnRueChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnIdProvinceChanging(string value);
    partial void OnIdProvinceChanged();
    partial void OnCodePostalChanging(string value);
    partial void OnCodePostalChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnCellulaireChanging(string value);
    partial void OnCellulaireChanged();
    partial void OnCourrielChanging(string value);
    partial void OnCourrielChanged();
    partial void OnSalaireHoraireChanging(int value);
    partial void OnSalaireHoraireChanged();
    partial void OnNoTypeEmployeChanging(int value);
    partial void OnNoTypeEmployeChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Employes()
		{
			this._Services = new EntitySet<Services>(new Action<Services>(this.attach_Services), new Action<Services>(this.detach_Services));
			this._Provinces = default(EntityRef<Provinces>);
			this._TypesEmploye = default(EntityRef<TypesEmploye>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotDePasse", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MotDePasse
		{
			get
			{
				return this._MotDePasse;
			}
			set
			{
				if ((this._MotDePasse != value))
				{
					this.OnMotDePasseChanging(value);
					this.SendPropertyChanging();
					this._MotDePasse = value;
					this.SendPropertyChanged("MotDePasse");
					this.OnMotDePasseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int NOT NULL")]
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCivique", DbType="Int NOT NULL")]
		public int NoCivique
		{
			get
			{
				return this._NoCivique;
			}
			set
			{
				if ((this._NoCivique != value))
				{
					this.OnNoCiviqueChanging(value);
					this.SendPropertyChanging();
					this._NoCivique = value;
					this.SendPropertyChanged("NoCivique");
					this.OnNoCiviqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this.OnRueChanging(value);
					this.SendPropertyChanging();
					this._Rue = value;
					this.SendPropertyChanged("Rue");
					this.OnRueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProvince", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string IdProvince
		{
			get
			{
				return this._IdProvince;
			}
			set
			{
				if ((this._IdProvince != value))
				{
					if (this._Provinces.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProvinceChanging(value);
					this.SendPropertyChanging();
					this._IdProvince = value;
					this.SendPropertyChanged("IdProvince");
					this.OnIdProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostal", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string CodePostal
		{
			get
			{
				return this._CodePostal;
			}
			set
			{
				if ((this._CodePostal != value))
				{
					this.OnCodePostalChanging(value);
					this.SendPropertyChanging();
					this._CodePostal = value;
					this.SendPropertyChanged("CodePostal");
					this.OnCodePostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cellulaire", DbType="VarChar(15)")]
		public string Cellulaire
		{
			get
			{
				return this._Cellulaire;
			}
			set
			{
				if ((this._Cellulaire != value))
				{
					this.OnCellulaireChanging(value);
					this.SendPropertyChanging();
					this._Cellulaire = value;
					this.SendPropertyChanged("Cellulaire");
					this.OnCellulaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Courriel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Courriel
		{
			get
			{
				return this._Courriel;
			}
			set
			{
				if ((this._Courriel != value))
				{
					this.OnCourrielChanging(value);
					this.SendPropertyChanging();
					this._Courriel = value;
					this.SendPropertyChanged("Courriel");
					this.OnCourrielChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaireHoraire", DbType="Int NOT NULL")]
		public int SalaireHoraire
		{
			get
			{
				return this._SalaireHoraire;
			}
			set
			{
				if ((this._SalaireHoraire != value))
				{
					this.OnSalaireHoraireChanging(value);
					this.SendPropertyChanging();
					this._SalaireHoraire = value;
					this.SendPropertyChanged("SalaireHoraire");
					this.OnSalaireHoraireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTypeEmploye", DbType="Int NOT NULL")]
		public int NoTypeEmploye
		{
			get
			{
				return this._NoTypeEmploye;
			}
			set
			{
				if ((this._NoTypeEmploye != value))
				{
					if (this._TypesEmploye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoTypeEmployeChanging(value);
					this.SendPropertyChanging();
					this._NoTypeEmploye = value;
					this.SendPropertyChanged("NoTypeEmploye");
					this.OnNoTypeEmployeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employes_Services", Storage="_Services", ThisKey="No", OtherKey="NoEmploye")]
		public EntitySet<Services> Services
		{
			get
			{
				return this._Services;
			}
			set
			{
				this._Services.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provinces_Employes", Storage="_Provinces", ThisKey="IdProvince", OtherKey="Id", IsForeignKey=true)]
		public Provinces Provinces
		{
			get
			{
				return this._Provinces.Entity;
			}
			set
			{
				Provinces previousValue = this._Provinces.Entity;
				if (((previousValue != value) 
							|| (this._Provinces.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provinces.Entity = null;
						previousValue.Employes.Remove(this);
					}
					this._Provinces.Entity = value;
					if ((value != null))
					{
						value.Employes.Add(this);
						this._IdProvince = value.Id;
					}
					else
					{
						this._IdProvince = default(string);
					}
					this.SendPropertyChanged("Provinces");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypesEmploye_Employes", Storage="_TypesEmploye", ThisKey="NoTypeEmploye", OtherKey="No", IsForeignKey=true)]
		public TypesEmploye TypesEmploye
		{
			get
			{
				return this._TypesEmploye.Entity;
			}
			set
			{
				TypesEmploye previousValue = this._TypesEmploye.Entity;
				if (((previousValue != value) 
							|| (this._TypesEmploye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TypesEmploye.Entity = null;
						previousValue.Employes.Remove(this);
					}
					this._TypesEmploye.Entity = value;
					if ((value != null))
					{
						value.Employes.Add(this);
						this._NoTypeEmploye = value.No;
					}
					else
					{
						this._NoTypeEmploye = default(int);
					}
					this.SendPropertyChanged("TypesEmploye");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Services(Services entity)
		{
			this.SendPropertyChanging();
			entity.Employes = this;
		}
		
		private void detach_Services(Services entity)
		{
			this.SendPropertyChanging();
			entity.Employes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PartiesJouees")]
	public partial class PartiesJouees : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdAbonnement;
		
		private int _NoTerrain;
		
		private System.DateTime _DatePartie;
		
		private int _Pointage;
		
		private string _Remarque;
		
		private EntityRef<Abonnements> _Abonnements;
		
		private EntityRef<Terrains> _Terrains;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAbonnementChanging(string value);
    partial void OnIdAbonnementChanged();
    partial void OnNoTerrainChanging(int value);
    partial void OnNoTerrainChanged();
    partial void OnDatePartieChanging(System.DateTime value);
    partial void OnDatePartieChanged();
    partial void OnPointageChanging(int value);
    partial void OnPointageChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public PartiesJouees()
		{
			this._Abonnements = default(EntityRef<Abonnements>);
			this._Terrains = default(EntityRef<Terrains>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAbonnement", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdAbonnement
		{
			get
			{
				return this._IdAbonnement;
			}
			set
			{
				if ((this._IdAbonnement != value))
				{
					if (this._Abonnements.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAbonnementChanging(value);
					this.SendPropertyChanging();
					this._IdAbonnement = value;
					this.SendPropertyChanged("IdAbonnement");
					this.OnIdAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTerrain", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NoTerrain
		{
			get
			{
				return this._NoTerrain;
			}
			set
			{
				if ((this._NoTerrain != value))
				{
					if (this._Terrains.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoTerrainChanging(value);
					this.SendPropertyChanging();
					this._NoTerrain = value;
					this.SendPropertyChanged("NoTerrain");
					this.OnNoTerrainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePartie", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DatePartie
		{
			get
			{
				return this._DatePartie;
			}
			set
			{
				if ((this._DatePartie != value))
				{
					this.OnDatePartieChanging(value);
					this.SendPropertyChanging();
					this._DatePartie = value;
					this.SendPropertyChanged("DatePartie");
					this.OnDatePartieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pointage", DbType="Int NOT NULL")]
		public int Pointage
		{
			get
			{
				return this._Pointage;
			}
			set
			{
				if ((this._Pointage != value))
				{
					this.OnPointageChanging(value);
					this.SendPropertyChanging();
					this._Pointage = value;
					this.SendPropertyChanged("Pointage");
					this.OnPointageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_PartiesJouees", Storage="_Abonnements", ThisKey="IdAbonnement", OtherKey="Id", IsForeignKey=true)]
		public Abonnements Abonnements
		{
			get
			{
				return this._Abonnements.Entity;
			}
			set
			{
				Abonnements previousValue = this._Abonnements.Entity;
				if (((previousValue != value) 
							|| (this._Abonnements.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Abonnements.Entity = null;
						previousValue.PartiesJouees.Remove(this);
					}
					this._Abonnements.Entity = value;
					if ((value != null))
					{
						value.PartiesJouees.Add(this);
						this._IdAbonnement = value.Id;
					}
					else
					{
						this._IdAbonnement = default(string);
					}
					this.SendPropertyChanged("Abonnements");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Terrains_PartiesJouees", Storage="_Terrains", ThisKey="NoTerrain", OtherKey="No", IsForeignKey=true)]
		public Terrains Terrains
		{
			get
			{
				return this._Terrains.Entity;
			}
			set
			{
				Terrains previousValue = this._Terrains.Entity;
				if (((previousValue != value) 
							|| (this._Terrains.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Terrains.Entity = null;
						previousValue.PartiesJouees.Remove(this);
					}
					this._Terrains.Entity = value;
					if ((value != null))
					{
						value.PartiesJouees.Add(this);
						this._NoTerrain = value.No;
					}
					else
					{
						this._NoTerrain = default(int);
					}
					this.SendPropertyChanged("Terrains");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PrixDepensesAbonnements")]
	public partial class PrixDepensesAbonnements : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NoTypeAbonnement;
		
		private int _Annee;
		
		private decimal _Prix;
		
		private decimal _DepensesObligatoires;
		
		private string _Remarque;
		
		private EntityRef<TypesAbonnement> _TypesAbonnement;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoTypeAbonnementChanging(int value);
    partial void OnNoTypeAbonnementChanged();
    partial void OnAnneeChanging(int value);
    partial void OnAnneeChanged();
    partial void OnPrixChanging(decimal value);
    partial void OnPrixChanged();
    partial void OnDepensesObligatoiresChanging(decimal value);
    partial void OnDepensesObligatoiresChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public PrixDepensesAbonnements()
		{
			this._TypesAbonnement = default(EntityRef<TypesAbonnement>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTypeAbonnement", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NoTypeAbonnement
		{
			get
			{
				return this._NoTypeAbonnement;
			}
			set
			{
				if ((this._NoTypeAbonnement != value))
				{
					if (this._TypesAbonnement.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoTypeAbonnementChanging(value);
					this.SendPropertyChanging();
					this._NoTypeAbonnement = value;
					this.SendPropertyChanged("NoTypeAbonnement");
					this.OnNoTypeAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annee", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Annee
		{
			get
			{
				return this._Annee;
			}
			set
			{
				if ((this._Annee != value))
				{
					this.OnAnneeChanging(value);
					this.SendPropertyChanging();
					this._Annee = value;
					this.SendPropertyChanged("Annee");
					this.OnAnneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prix", DbType="Money NOT NULL")]
		public decimal Prix
		{
			get
			{
				return this._Prix;
			}
			set
			{
				if ((this._Prix != value))
				{
					this.OnPrixChanging(value);
					this.SendPropertyChanging();
					this._Prix = value;
					this.SendPropertyChanged("Prix");
					this.OnPrixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepensesObligatoires", DbType="Money NOT NULL")]
		public decimal DepensesObligatoires
		{
			get
			{
				return this._DepensesObligatoires;
			}
			set
			{
				if ((this._DepensesObligatoires != value))
				{
					this.OnDepensesObligatoiresChanging(value);
					this.SendPropertyChanging();
					this._DepensesObligatoires = value;
					this.SendPropertyChanged("DepensesObligatoires");
					this.OnDepensesObligatoiresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypesAbonnement_PrixDepensesAbonnements", Storage="_TypesAbonnement", ThisKey="NoTypeAbonnement", OtherKey="No", IsForeignKey=true)]
		public TypesAbonnement TypesAbonnement
		{
			get
			{
				return this._TypesAbonnement.Entity;
			}
			set
			{
				TypesAbonnement previousValue = this._TypesAbonnement.Entity;
				if (((previousValue != value) 
							|| (this._TypesAbonnement.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TypesAbonnement.Entity = null;
						previousValue.PrixDepensesAbonnements.Remove(this);
					}
					this._TypesAbonnement.Entity = value;
					if ((value != null))
					{
						value.PrixDepensesAbonnements.Add(this);
						this._NoTypeAbonnement = value.No;
					}
					else
					{
						this._NoTypeAbonnement = default(int);
					}
					this.SendPropertyChanged("TypesAbonnement");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provinces")]
	public partial class Provinces : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Nom;
		
		private string _Remarque;
		
		private EntitySet<Abonnements> _Abonnements;
		
		private EntitySet<Employes> _Employes;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Provinces()
		{
			this._Abonnements = new EntitySet<Abonnements>(new Action<Abonnements>(this.attach_Abonnements), new Action<Abonnements>(this.detach_Abonnements));
			this._Employes = new EntitySet<Employes>(new Action<Employes>(this.attach_Employes), new Action<Employes>(this.detach_Employes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provinces_Abonnements", Storage="_Abonnements", ThisKey="Id", OtherKey="IdProvince")]
		public EntitySet<Abonnements> Abonnements
		{
			get
			{
				return this._Abonnements;
			}
			set
			{
				this._Abonnements.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provinces_Employes", Storage="_Employes", ThisKey="Id", OtherKey="IdProvince")]
		public EntitySet<Employes> Employes
		{
			get
			{
				return this._Employes;
			}
			set
			{
				this._Employes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Abonnements(Abonnements entity)
		{
			this.SendPropertyChanging();
			entity.Provinces = this;
		}
		
		private void detach_Abonnements(Abonnements entity)
		{
			this.SendPropertyChanging();
			entity.Provinces = null;
		}
		
		private void attach_Employes(Employes entity)
		{
			this.SendPropertyChanging();
			entity.Provinces = this;
		}
		
		private void detach_Employes(Employes entity)
		{
			this.SendPropertyChanging();
			entity.Provinces = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reabonnements")]
	public partial class Reabonnements : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdAbonnement;
		
		private System.DateTime _DateRenouvellement;
		
		private string _Remarque;
		
		private EntityRef<Abonnements> _Abonnements;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAbonnementChanging(string value);
    partial void OnIdAbonnementChanged();
    partial void OnDateRenouvellementChanging(System.DateTime value);
    partial void OnDateRenouvellementChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Reabonnements()
		{
			this._Abonnements = default(EntityRef<Abonnements>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAbonnement", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdAbonnement
		{
			get
			{
				return this._IdAbonnement;
			}
			set
			{
				if ((this._IdAbonnement != value))
				{
					if (this._Abonnements.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAbonnementChanging(value);
					this.SendPropertyChanging();
					this._IdAbonnement = value;
					this.SendPropertyChanged("IdAbonnement");
					this.OnIdAbonnementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRenouvellement", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateRenouvellement
		{
			get
			{
				return this._DateRenouvellement;
			}
			set
			{
				if ((this._DateRenouvellement != value))
				{
					this.OnDateRenouvellementChanging(value);
					this.SendPropertyChanging();
					this._DateRenouvellement = value;
					this.SendPropertyChanged("DateRenouvellement");
					this.OnDateRenouvellementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Abonnements_Reabonnements", Storage="_Abonnements", ThisKey="IdAbonnement", OtherKey="Id", IsForeignKey=true)]
		public Abonnements Abonnements
		{
			get
			{
				return this._Abonnements.Entity;
			}
			set
			{
				Abonnements previousValue = this._Abonnements.Entity;
				if (((previousValue != value) 
							|| (this._Abonnements.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Abonnements.Entity = null;
						previousValue.Reabonnements.Remove(this);
					}
					this._Abonnements.Entity = value;
					if ((value != null))
					{
						value.Reabonnements.Add(this);
						this._IdAbonnement = value.Id;
					}
					else
					{
						this._IdAbonnement = default(string);
					}
					this.SendPropertyChanged("Abonnements");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Services")]
	public partial class Services : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _TypesService;
		
		private int _NoEmploye;
		
		private string _Remarque;
		
		private EntitySet<Depenses> _Depenses;
		
		private EntityRef<Employes> _Employes;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnTypesServiceChanging(string value);
    partial void OnTypesServiceChanged();
    partial void OnNoEmployeChanging(int value);
    partial void OnNoEmployeChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Services()
		{
			this._Depenses = new EntitySet<Depenses>(new Action<Depenses>(this.attach_Depenses), new Action<Depenses>(this.detach_Depenses));
			this._Employes = default(EntityRef<Employes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypesService", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TypesService
		{
			get
			{
				return this._TypesService;
			}
			set
			{
				if ((this._TypesService != value))
				{
					this.OnTypesServiceChanging(value);
					this.SendPropertyChanging();
					this._TypesService = value;
					this.SendPropertyChanged("TypesService");
					this.OnTypesServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoEmploye", DbType="Int NOT NULL")]
		public int NoEmploye
		{
			get
			{
				return this._NoEmploye;
			}
			set
			{
				if ((this._NoEmploye != value))
				{
					if (this._Employes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoEmployeChanging(value);
					this.SendPropertyChanging();
					this._NoEmploye = value;
					this.SendPropertyChanged("NoEmploye");
					this.OnNoEmployeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Services_Depenses", Storage="_Depenses", ThisKey="No", OtherKey="NoService")]
		public EntitySet<Depenses> Depenses
		{
			get
			{
				return this._Depenses;
			}
			set
			{
				this._Depenses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employes_Services", Storage="_Employes", ThisKey="NoEmploye", OtherKey="No", IsForeignKey=true)]
		public Employes Employes
		{
			get
			{
				return this._Employes.Entity;
			}
			set
			{
				Employes previousValue = this._Employes.Entity;
				if (((previousValue != value) 
							|| (this._Employes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employes.Entity = null;
						previousValue.Services.Remove(this);
					}
					this._Employes.Entity = value;
					if ((value != null))
					{
						value.Services.Add(this);
						this._NoEmploye = value.No;
					}
					else
					{
						this._NoEmploye = default(int);
					}
					this.SendPropertyChanged("Employes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Depenses(Depenses entity)
		{
			this.SendPropertyChanging();
			entity.Services = this;
		}
		
		private void detach_Depenses(Depenses entity)
		{
			this.SendPropertyChanging();
			entity.Services = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Terrains")]
	public partial class Terrains : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _Nom;
		
		private int _NombreTrous;
		
		private string _Description;
		
		private string _Remarque;
		
		private EntitySet<PartiesJouees> _PartiesJouees;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnNombreTrousChanging(int value);
    partial void OnNombreTrousChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public Terrains()
		{
			this._PartiesJouees = new EntitySet<PartiesJouees>(new Action<PartiesJouees>(this.attach_PartiesJouees), new Action<PartiesJouees>(this.detach_PartiesJouees));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreTrous", DbType="Int NOT NULL")]
		public int NombreTrous
		{
			get
			{
				return this._NombreTrous;
			}
			set
			{
				if ((this._NombreTrous != value))
				{
					this.OnNombreTrousChanging(value);
					this.SendPropertyChanging();
					this._NombreTrous = value;
					this.SendPropertyChanged("NombreTrous");
					this.OnNombreTrousChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Terrains_PartiesJouees", Storage="_PartiesJouees", ThisKey="No", OtherKey="NoTerrain")]
		public EntitySet<PartiesJouees> PartiesJouees
		{
			get
			{
				return this._PartiesJouees;
			}
			set
			{
				this._PartiesJouees.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PartiesJouees(PartiesJouees entity)
		{
			this.SendPropertyChanging();
			entity.Terrains = this;
		}
		
		private void detach_PartiesJouees(PartiesJouees entity)
		{
			this.SendPropertyChanging();
			entity.Terrains = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TypesAbonnement")]
	public partial class TypesAbonnement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _Description;
		
		private string _Remarque;
		
		private EntitySet<Abonnements> _Abonnements;
		
		private EntitySet<PrixDepensesAbonnements> _PrixDepensesAbonnements;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public TypesAbonnement()
		{
			this._Abonnements = new EntitySet<Abonnements>(new Action<Abonnements>(this.attach_Abonnements), new Action<Abonnements>(this.detach_Abonnements));
			this._PrixDepensesAbonnements = new EntitySet<PrixDepensesAbonnements>(new Action<PrixDepensesAbonnements>(this.attach_PrixDepensesAbonnements), new Action<PrixDepensesAbonnements>(this.detach_PrixDepensesAbonnements));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypesAbonnement_Abonnements", Storage="_Abonnements", ThisKey="No", OtherKey="NoTypeAbonnement")]
		public EntitySet<Abonnements> Abonnements
		{
			get
			{
				return this._Abonnements;
			}
			set
			{
				this._Abonnements.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypesAbonnement_PrixDepensesAbonnements", Storage="_PrixDepensesAbonnements", ThisKey="No", OtherKey="NoTypeAbonnement")]
		public EntitySet<PrixDepensesAbonnements> PrixDepensesAbonnements
		{
			get
			{
				return this._PrixDepensesAbonnements;
			}
			set
			{
				this._PrixDepensesAbonnements.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Abonnements(Abonnements entity)
		{
			this.SendPropertyChanging();
			entity.TypesAbonnement = this;
		}
		
		private void detach_Abonnements(Abonnements entity)
		{
			this.SendPropertyChanging();
			entity.TypesAbonnement = null;
		}
		
		private void attach_PrixDepensesAbonnements(PrixDepensesAbonnements entity)
		{
			this.SendPropertyChanging();
			entity.TypesAbonnement = this;
		}
		
		private void detach_PrixDepensesAbonnements(PrixDepensesAbonnements entity)
		{
			this.SendPropertyChanging();
			entity.TypesAbonnement = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TypesEmploye")]
	public partial class TypesEmploye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _Description;
		
		private string _Remarque;
		
		private EntitySet<Employes> _Employes;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnRemarqueChanging(string value);
    partial void OnRemarqueChanged();
    #endregion
		
		public TypesEmploye()
		{
			this._Employes = new EntitySet<Employes>(new Action<Employes>(this.attach_Employes), new Action<Employes>(this.detach_Employes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarque", DbType="VarChar(50)")]
		public string Remarque
		{
			get
			{
				return this._Remarque;
			}
			set
			{
				if ((this._Remarque != value))
				{
					this.OnRemarqueChanging(value);
					this.SendPropertyChanging();
					this._Remarque = value;
					this.SendPropertyChanged("Remarque");
					this.OnRemarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypesEmploye_Employes", Storage="_Employes", ThisKey="No", OtherKey="NoTypeEmploye")]
		public EntitySet<Employes> Employes
		{
			get
			{
				return this._Employes;
			}
			set
			{
				this._Employes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Employes(Employes entity)
		{
			this.SendPropertyChanging();
			entity.TypesEmploye = this;
		}
		
		private void detach_Employes(Employes entity)
		{
			this.SendPropertyChanging();
			entity.TypesEmploye = null;
		}
	}
}
#pragma warning restore 1591
